[pack]
path = "packs/yamis"
name = "yamis"

[colors]
# scheme = "~/.themes/my.colors"
# matugen = "/tmp/matugen.json"
# manual = "~/.config/miconium/colors.toml"

[export]
output = "~/.local/share/icons/Miconium"

[gui]
window_width = 800
window_height = 600
