use std::path::{Path, PathBuf};
use std::sync::mpsc;

use crate::color::Palette;
use crate::config::ExportConfig;
use crate::pack::Pack;
use crate::svg_engine;

use thiserror::Error;

#[derive(Debug, Error)]
pub enum ExportError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("SVG assembly error: {0}")]
    Svg(#[from] svg_engine::SvgError),
    #[error("no frames available in pack")]
    NoFrames,
    #[error("symlink error: {0}")]
    Symlink(String),
}

#[derive(Debug, Clone)]
pub struct ExportProgress {
    pub category: String,
    pub current: usize,
    pub total: usize,
    pub message: String,
}

const AUTHORS_CONTENT: &str = "\
----------------------------------------
Generated by Miconium
https://github.com/Y-Akamirsky/miconium
----------------------------------------
";

const GPLV3_LICENSE: &str = "\
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.
";

fn category_to_output_dir(category: &str) -> &str {
    match category {
        "apps" => "apps",
        "categories" => "categories",
        "devices" => "devices",
        "emblems" => "emblems",
        "mime" => "mimetypes",
        "preferences" => "preferences",
        "status" => "status",
        _ => category,
    }
}

fn create_output_tree(output: &Path, with_symlinks: bool) -> Result<(), ExportError> {
    let categories = [
        "actions", "apps", "categories", "devices", "emblems",
        "mimetypes", "places", "preferences", "status",
    ];
    for cat in &categories {
        std::fs::create_dir_all(output.join(cat).join("scalable"))?;
    }

    if with_symlinks {
        let link = output.join("places").join("16");
        if !link.exists() {
            symlink_scalable(&link)?;
        }
    }

    Ok(())
}

#[cfg(unix)]
fn symlink_scalable(link: &Path) -> Result<(), ExportError> {
    std::os::unix::fs::symlink("scalable", link)
        .map_err(|e| ExportError::Symlink(format!("{} -> scalable: {e}", link.display())))
}

#[cfg(not(unix))]
fn symlink_scalable(_link: &Path) -> Result<(), ExportError> {
    Ok(())
}

fn write_meta_files(output: &Path, project_root: &Path) -> Result<(), ExportError> {
    std::fs::write(output.join("Authors"), AUTHORS_CONTENT)?;

    let index_src = project_root.join("index.theme");
    if index_src.is_file() {
        std::fs::copy(&index_src, output.join("index.theme"))?;
    }

    let license_src = project_root.join("LICENSE");
    if license_src.is_file() {
        std::fs::copy(&license_src, output.join("LICENSE"))?;
    } else {
        std::fs::write(output.join("LICENSE"), GPLV3_LICENSE)?;
    }

    Ok(())
}

fn write_icon(output: &Path, category: &str, icon: &svg_engine::AssembledIcon, filename: &str) -> Result<(), ExportError> {
    let dir = category_to_output_dir(category);
    let filename = format!("{filename}.svg");
    let path = output.join(dir).join("scalable").join(&filename);
    std::fs::write(&path, &icon.svg)?;
    Ok(())
}

pub fn export_pack(
    pack: &Pack,
    palette: &Palette,
    export_cfg: &ExportConfig,
    project_root: &Path,
    progress_tx: &mpsc::Sender<ExportProgress>,
) -> Result<(), ExportError> {
    let output_path = resolve_output_path(export_cfg);

    let frame = pack
        .frames
        .colorizable
        .first()
        .cloned()
        .ok_or(ExportError::NoFrames)?;

    create_output_tree(&output_path, export_cfg.generate_16_symlinks)?;

    let signs = pack.all_signs();
    let total_icons: usize = signs.values().map(Vec::len).sum();
    let mut processed = 0usize;

    for (category, icons) in &signs {
        for sign in icons {
            let assembled = svg_engine::assemble_icon(&frame, sign, &pack.accessories, palette)?;
            write_icon(&output_path, category, &assembled, &sign.name)?;

            processed += 1;
            let _ = progress_tx.send(ExportProgress {
                category: category.clone(),
                current: processed,
                total: total_icons,
                message: format!("{}: {}", category, sign.name),
            });
        }
    }

    write_meta_files(&output_path, project_root)?;

    Ok(())
}

fn resolve_output_path(config: &ExportConfig) -> PathBuf {
    if let Some(path) = &config.output {
        if path.starts_with('~') {
            let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
            let mut buf = PathBuf::from(home);
            buf.push(path.strip_prefix('~').unwrap_or(""));
            buf
        } else {
            PathBuf::from(path)
        }
    } else {
        let home = std::env::var("HOME").unwrap_or_else(|_| "/tmp".into());
        PathBuf::from(home).join(".local/share/icons/Miconium")
    }
}

#[cfg(test)]
mod tests;
