use std::collections::HashMap;
use std::path::{Path, PathBuf};
use std::sync::mpsc;

use crate::color::Palette;
use crate::config::{CategoryOverride, ExportConfig};
use crate::pack::Pack;
use crate::svg_engine::{self, LayerTransform};

use thiserror::Error;

#[derive(Debug, Error)]
pub enum ExportError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("SVG assembly error: {0}")]
    Svg(#[from] svg_engine::SvgError),
    #[error("no frames available in pack")]
    NoFrames,
    #[error("symlink error: {0}")]
    Symlink(String),
    #[error("icon cache update failed: {0}")]
    CacheUpdate(String),
}

#[derive(Debug, Clone)]
pub struct ExportProgress {
    pub category: String,
    pub variant: String,
    pub current: usize,
    pub total: usize,
    pub message: String,
}

const AUTHORS_CONTENT: &str = "\
----------------------------------------
Generated by Miconium
https://github.com/Y-Akamirsky/miconium
----------------------------------------
";

const GPLV3_LICENSE: &str = "\
                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007

 Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.
";

fn create_output_tree(output: &Path, pack: &Pack) -> Result<(), ExportError> {
    std::fs::create_dir_all(output)?;
    for cat in pack.categories() {
        for variant in pack.get_category_variants(&cat) {
            std::fs::create_dir_all(output.join(&cat).join(&variant))?;
        }
    }
    Ok(())
}

fn context_for_category(cat: &str) -> &str {
    match cat {
        "actions" => "Actions",
        "categories" => "Categories",
        "devices" => "Devices",
        "emblems" => "Emblems",
        "mimetypes" => "MimeTypes",
        "places" => "Places",
        "preferences" => "Preferences",
        "status" => "Status",
        _ => "Applications",
    }
}

fn scalable_section_size(category: &str) -> u32 {
    if category == "status" { 64 } else { 96 }
}

fn scalable_section_min_size(category: &str) -> u32 {
    match category {
        "status" => 16,
        _ => 8,
    }
}

fn scalable_section_max_size(category: &str) -> u32 {
    match category {
        "mimetypes" => 256,
        "status" => 128,
        _ => 512,
    }
}

fn generate_dir_section(category: &str, variant: &str) -> String {
    let context = context_for_category(category);
    let is_numbered = variant.chars().all(|c| c.is_ascii_digit());

    let (size, min_size, max_size) = if is_numbered {
        let s: u32 = variant.parse().unwrap_or(16);
        (s, s.min(8), (s * 2).max(32))
    } else {
        (
            scalable_section_size(category),
            scalable_section_min_size(category),
            scalable_section_max_size(category),
        )
    };

    format!(
        "[{category}/{variant}]\n\
         Size={size}\n\
         Context={context}\n\
         MinSize={min_size}\n\
         MaxSize={max_size}\n\
         Type=Scalable\n"
    )
}

fn generate_index_theme(pack: &Pack) -> String {
    let mut dirs: Vec<String> = Vec::new();
    let mut sections: Vec<String> = Vec::new();

    for cat in pack.categories() {
        for variant in pack.get_category_variants(&cat) {
            let dir = format!("{cat}/{variant}");
            dirs.push(dir);
            sections.push(generate_dir_section(&cat, &variant));
        }
    }

    format!(
        "[Icon Theme]\n\
         Name=Miconium\n\
         Comment=SVG icon generator for Linux desktop.\n\
         Inherits=hicolor\n\
         FollowsColorScheme=true\n\
         \n\
         Directories={}\n\
         \n\
         {}",
        dirs.join(","),
        sections.join("\n"),
    )
}

fn write_meta_files(output: &Path, pack: &Pack, project_root: &Path) -> Result<(), ExportError> {
    std::fs::write(output.join("Authors"), AUTHORS_CONTENT)?;
    std::fs::write(output.join("index.theme"), generate_index_theme(pack))?;

    let license_src = project_root.join("LICENSE");
    if license_src.is_file() {
        std::fs::copy(&license_src, output.join("LICENSE"))?;
    } else {
        std::fs::write(output.join("LICENSE"), GPLV3_LICENSE)?;
    }

    Ok(())
}

fn write_icon(output: &Path, category: &str, variant: &str, icon: &svg_engine::AssembledIcon, filename: &str) -> Result<(), ExportError> {
    let filename = format!("{filename}.svg");
    let path = output.join(category).join(variant).join(&filename);
    std::fs::write(&path, &icon.svg)?;
    Ok(())
}

fn run_export(
    output_path: &Path,
    pack: &Pack,
    palette: &Palette,
    category_overrides: &HashMap<String, HashMap<String, CategoryOverride>>,
    project_root: &Path,
    progress_tx: &mpsc::Sender<ExportProgress>,
) -> Result<(), ExportError> {
    create_output_tree(output_path, pack)?;

    let total_icons: usize = pack.categories().iter()
        .map(|cat| {
            pack.get_category_variants(cat).iter()
                .map(|variant| pack.get_sign_variant(cat, variant).len())
                .sum::<usize>()
        })
        .sum();
    let mut processed = 0usize;

    for category in &pack.categories() {
        for variant in pack.get_category_variants(category) {
            let cat_overrides = category_overrides.get(category)
                .and_then(|v| v.get(&variant))
                .cloned()
                .unwrap_or_else(|| crate::config::default_category_override(category));

            let (frame_data, frame_is_static) = resolve_frame(&cat_overrides, pack)?;

            let accessories: Vec<crate::pack::LayerData> = if cat_overrides.show_accessories {
                cat_overrides
                    .accessories
                    .iter()
                    .filter_map(|ac| pack.accessories.iter().find(|a| a.name == ac.name).cloned())
                    .collect()
            } else {
                Vec::new()
            };

            let accessory_transforms: Vec<Option<LayerTransform>> = if cat_overrides.show_accessories {
                cat_overrides
                    .accessories
                    .iter()
                    .map(|ac| if ac.has_offset() { Some(ac.layer_transform()) } else { None })
                    .collect()
            } else {
                Vec::new()
            };

            let icons = pack.get_sign_variant(category, &variant);
            for sign in &icons {
                let assembled = svg_engine::assemble_icon(
                    &frame_data,
                    sign,
                    &accessories,
                    &accessory_transforms,
                    palette,
                    cat_overrides.show_frame,
                    cat_overrides.show_accessories,
                    frame_is_static,
                    cat_overrides.frame_scale,
                    cat_overrides.icon_scale,
                    cat_overrides.acc_scale,
                )?;
                write_icon(output_path, category, &variant, &assembled, &sign.name)?;

                processed += 1;
                let _ = progress_tx.send(ExportProgress {
                    category: category.clone(),
                    variant: variant.clone(),
                    current: processed,
                    total: total_icons,
                    message: format!("{} / {}: {}", category, variant, sign.name),
                });
            }
        }
    }

    write_meta_files(output_path, pack, project_root)?;

    Ok(())
}

fn resolve_frame(ov: &CategoryOverride, pack: &Pack) -> Result<(crate::pack::LayerData, bool), ExportError> {
    if !ov.show_frame {
        return Ok((crate::pack::LayerData {
            svg_content: String::new(),
            name: "none".into(),
        }, false));
    }

    match ov.frame_source.as_str() {
        "static_dark" => {
            if let Some(ref name) = ov.selected_static_frame {
                if let Some(ref sf) = pack.frames.static_frames {
                    if let Some(frame) = sf.dark.iter().find(|f| f.name == *name) {
                        return Ok((frame.clone(), true));
                    }
                    eprintln!("Warning: static (dark) frame '{name}' not found, falling back");
                }
            }
            if let Some(ref sf) = pack.frames.static_frames {
                if let Some(frame) = sf.dark.first() {
                    return Ok((frame.clone(), true));
                }
            }
            eprintln!("Warning: no dark static frames available, falling back to colorizable");
            let frame = pack.frames.colorizable.first().cloned().ok_or(ExportError::NoFrames)?;
            Ok((frame, false))
        }
        "static_light" => {
            if let Some(ref name) = ov.selected_static_frame {
                if let Some(ref sf) = pack.frames.static_frames {
                    if let Some(frame) = sf.light.iter().find(|f| f.name == *name) {
                        return Ok((frame.clone(), true));
                    }
                    eprintln!("Warning: static (light) frame '{name}' not found, falling back");
                }
            }
            if let Some(ref sf) = pack.frames.static_frames {
                if let Some(frame) = sf.light.first() {
                    return Ok((frame.clone(), true));
                }
            }
            eprintln!("Warning: no light static frames available, falling back to colorizable");
            let frame = pack.frames.colorizable.first().cloned().ok_or(ExportError::NoFrames)?;
            Ok((frame, false))
        }
        _ => {
            let first_colorizable = pack.frames.colorizable.first();
            if let Some(name) = ov.selected_frame.as_deref() {
                if let Some(frame) = pack.frames.colorizable.iter().find(|f| f.name == name) {
                    return Ok((frame.clone(), false));
                }
                eprintln!("Warning: frame '{name}' not found, falling back to first colorizable");
            }
            let frame = first_colorizable.cloned().ok_or(ExportError::NoFrames)?;
            Ok((frame, false))
        }
    }
}

#[allow(clippy::implicit_hasher)]
pub fn export_pack(
    pack: &Pack,
    palette: &Palette,
    export_cfg: &ExportConfig,
    category_overrides: &HashMap<String, HashMap<String, CategoryOverride>>,
    project_root: &Path,
    progress_tx: &mpsc::Sender<ExportProgress>,
) -> Result<PathBuf, ExportError> {
    let output_path = resolve_output_path(export_cfg);

    match run_export(&output_path, pack, palette, category_overrides, project_root, progress_tx) {
        Ok(()) => Ok(output_path),
        Err(ExportError::Io(_)) => {
            let fallback = PathBuf::from("/tmp/miconium-export");
            eprintln!("Export: IO error on {}, retrying with {}", output_path.display(), fallback.display());
            run_export(&fallback, pack, palette, category_overrides, project_root, progress_tx)?;
            Ok(fallback)
        }
        Err(e) => Err(e),
    }
}

/// Run `gtk-update-icon-cache -f <dir>` to refresh the icon theme cache after
/// a successful "Apply" export. Fails (without panicking) when the tool is
/// missing or exits non-zero, so callers can warn the user.
pub fn refresh_icon_cache(theme_dir: &Path) -> Result<(), ExportError> {
    let result = std::process::Command::new("gtk-update-icon-cache")
        .arg("-f")
        .arg(theme_dir)
        .output();
    match result {
        Ok(output) if output.status.success() => Ok(()),
        Ok(output) => Err(ExportError::CacheUpdate(format!(
            "gtk-update-icon-cache exited with {status}: {err}",
            status = output.status,
            err = String::from_utf8_lossy(&output.stderr).trim(),
        ))),
        Err(e) => Err(ExportError::CacheUpdate(e.to_string())),
    }
}

#[must_use]
pub fn resolve_output_path(config: &ExportConfig) -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_default();
    let fallback = || PathBuf::from("/tmp/miconium-export");
    if let Some(path) = &config.output {
        if path.starts_with('~') {
            let mut buf = if home.is_empty() { return fallback(); } else { PathBuf::from(&home) };
            let suffix = path.strip_prefix('~').unwrap_or("");
            let suffix = suffix.strip_prefix('/').unwrap_or(suffix);
            buf.push(suffix);
            buf
        } else {
            PathBuf::from(path)
        }
    } else if home.is_empty() {
        fallback()
    } else {
        PathBuf::from(home).join(".local/share/icons/Miconium")
    }
}

#[cfg(test)]
mod tests;
